### PR TITLE
[fs] Instrumentation

### PR DESCRIPTION
**Pull request by Qard**
This introduces fs tracing. I need to expand the test coverage, but everything works so far. :+1: 

We should also solidify a file system spec before I go much further.

### CODE REVIEW

**Comment by Qard** [comment]
@MikeA- 

This seems like a good time to bring up the streams topic again. `fs.createReadStream()` and `fs.createWriteStream()` are somewhat commonly used to move file system reads and writes through memory quickly. We should think about if this is something we can instrument well.

**Comment by MikeA-** [comment]
wondering what those methods ( createReadStream, createWriteStream ) are doing - the act of creating a stream itself I wouldn't expect a bunch of latency on, is there more happening besides that when they are invoked?  While it would give good insight into "profiling" what was executing, unsure of the value of them as extents.

**Comment by Qard** [comment]
The creation itself is not really valuable, it's the movement of data through streams that I think would be valuable. I'm not sure how to represent it though. From a code perspective, it generally looks something like this:

```js
var sourceFile = fs.createReadStream('from.txt')
var destinationFile = fs.createWriteStream('to.txt')

sourceFile.pipe(destinationFile)
```

There's a lot of magic in there though, as it basically constructs an event pipeline that reads and writes in chunks, so the entire file doesn't get loaded into memory.

So some possibilities are reporting the "start" and "end" of the entire stream, or to report individual chunk events. Chunk events would likely get pretty noisy.

**Comment by MikeA-** [comment]
Feeling like we'd want to play around with stream reporting at a different time.  Been through this before in various other languages and haven't found a useful representation yet, as the chunks can get noisy.  Capturing the start/end of the stream reading/writing may be nice, but I think that exploration can happen after we've instrumented fs and fleshed out what we'll report including keys.  I don't think we want to report create*Stream extents is my initial thought.  What do you think?

**Comment by Qard** [comment]
Agreed, the create functions are not valuable. I just wanted to check if we needed to restart the streams discussion for this. I wasn't implying we block the release for it or anything. :)

**Pull request merged**
