### PR TITLE
[koa] Instrumentation

### PR DESCRIPTION
**Pull request by Qard**
I've got most of the more popular co/koa components instrumented. Need to get some tests written now.

### CODE REVIEW

**Comment by Qard** [comment]
Dumping a whole bunch of traces. The koa instrumentation supports multiple routers, so I've got traces for each.

[koa-route](http://npmjs.org/package/koa-route):
- [POST /todos](https://stephenappneta.tv.appneta.com/traces/view/E962AB8C1A4A61F201958C665E51082EA4106DA0#)
- [GET /todos](https://stephenappneta.tv.appneta.com/traces/view/E9B941BE24C7BCFC983D50AF5C43584A01688A70#)
- [PUT /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/6BD35FB2F9FCD40B9E40A0D545509507E019FE38#)
- [GET /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/756A13CCD70D6538EE97F34009F40A89E4653434#)
- [DELETE /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/67986203C4CD566E2F7BE286F21AF6A176468C7C#)

[koa-router](http://npmjs.org/package/koa-router):
- [POST /todos](https://stephenappneta.tv.appneta.com/traces/view/7770AEB65E34FC65206EFA361C3C885205A9386F#)
- [GET /todos](https://stephenappneta.tv.appneta.com/traces/view/C91E4E6157364CA571181E648355234C07D2C842#)
- [PUT /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/2ACCA9F874628D805D119C19450C6687FA2BD153#)
- [GET /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/18C6EFAF993979A93288AFC3CCE0C09E495C685A#)
- [DELETE /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/C11D9643406D7D5B55A4904C3A101025099931D7#)

[koa-resource-router](http://npmjs.org/package/koa-resource-router):
- [POST /todos](https://stephenappneta.tv.appneta.com/traces/view/75A54B9FAD093B69BB69AA53D29D735A705179E3#)
- [GET /todos](https://stephenappneta.tv.appneta.com/traces/view/686CFE9EB9C8014C972D1EDABBA4C4CCD6A1BA45#)
- [PUT /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/5C1DD767CD14A3AB5B624F167A087211295DBC81#)
- [GET /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/E42633088887949B37B787EA35BF81821D7B7015#)
- [DELETE /todos/:todo](https://stephenappneta.tv.appneta.com/traces/view/9929ADDEF84478FAD89910989EE2CD61F907D18C#)

**Comment by MikeA-** [comment]
Looking great @Qard !

Was wondering about the "co-render" layer https://stephenappneta.tv.appneta.com/traces/view/E9B941BE24C7BCFC983D50AF5C43584A01688A70/3   It stuck out to me because I was expecting "koa-render", but I guess this reflects that different template engines can be used with koa?

Also, what is the difference of "koa-route" and "koa-router" and "koa-resource-router?  The traces look similar, different internal implementations?

**Comment by Qard** [comment]
Yep. The layer is called co-render because the module that does the rendering is co-render, not koa itself--it has no internal concept of rendering. As for the routing modules: koa-route is an external router than just adds extra logic to each possible route and generates a regular middleware, koa-router monkey-patches koa itself for express-style routing, and koa-resource-router builds traditional controller-style mountable middlewares.

**Comment by Qard** [comment]
Current version support:
- koa - 0.0.1+ (2013-11-06)
- koa-route - 1.0.1+ (2013-11-16)
- koa-router - 1.6.0+ (2013-12-18)
- koa-resource-router - all
- co-render - all

**Pull request merged**
