### PR TITLE
Fix exception in koa-router 5.4

### PR DESCRIPTION
**Pull request by adam-hert**
This PR does some quick sanity checks to see if the app object exists before running a filter method.

### CODE REVIEW

**Comment by MikeA-** [comment]
nice @adam-hert - can you add something to the tests that exercises this scenario?

**Comment by Qard** [comment]
I believe it's just related to the specific version of koa-router, so it should already be surfaced by the support matrix tests.

BTW, It's probably simpler to just replace `[handler, app]` with `(app ? [handler, app] : [handler])`.

**Comment by adam-hert** [comment]
@Qard good catch, I cleaned it up with you solution

**Comment by Qard** [comment]
Can you fix the indentation on lines 20 and 23 too, please?

**Comment by adam-hert** [comment]
@Qard Done :)

**Comment by Qard** [comment]
Fixed and released as 2.7.1.

**Pull request merged**
