### PR TITLE
[amqp] Instrumentation

### PR DESCRIPTION
**Pull request by Qard**
This is a quick spike on getting some amqp instrumentation.

### CODE REVIEW

**Comment by Qard** [comment]
@MikeA- Here's a sample trace:

https://stephenappneta.tv.appneta.com/traces/view/47E17F178A66FC037A28BECF47F9EA3B04E2841D/3#tt=raw

Any other data you'd like to see in there?

**Comment by MikeA-** [comment]
What about your thoughts on an action?  Add an ExchangeAction = publish ?  any value in that?

We briefly discussed this, if there was a message id/key, that could be cool for tracking end-2-end processing, even though we're just capturing publish now.

**Comment by Qard** [comment]
I can add ExchangeAction. RoutingKey would also probably be good.

**Comment by Qard** [comment]
Here's an updated trace: https://stephenappneta.tv.appneta.com/traces/view/5F246EAA09BCB4BA539A3064F7B8066975844BE4/3#tt=raw

**Pull request merged**
