### PR TITLE
[mssql] Instrumentation

### PR DESCRIPTION
**Pull request by Qard**
This includes instrumentation for [tedious](https://www.npmjs.org/package/tedious), the main mssql driver for node.

### CODE REVIEW

**Comment by Qard** [comment]
This currently works for 1.5.3-1.8.1, which goes back as far as October. For context, 1.0.0 was in July.

**Comment by Qard** [comment]
Here's a sample trace: https://stephenappneta.tv.appneta.com/traces/view/CCF9B88A59380DA2811F293FCC6DA5987F3640BF/1-0

**Comment by Qard** [comment]
This currently works for 0.0.4-1.8.1, which goes back as far as 2012-04-15.

**Comment by MikeA-** [comment]
thanks @Qard - could you also provide sample traces that show the sanitization in action, and how about edge cases ( like param size constraints > 1000K ) - anything to demonstrate there?

**Comment by Qard** [comment]
Yep, I can do that. :)

**Comment by Qard** [comment]
Here's some more sample traces.

Sanitization: https://stephenappneta.tv.appneta.com/traces/view/E996EE3DDC5EC040D6BDA237CFFEA267DCAF0C94/1-0

Query length trimming:
https://stephenappneta.tv.appneta.com/traces/view/5E638A96BD61F744C5CB1DD9F1DBB586686811B4/1-0

**Comment by MikeA-** [comment]
Thanks!  Couple of small things:  when the query is truncated, a key should be sent to indicate that ie. QueryTruncated : true.  For the sanitization, when sanitization is on, the QueryArgs key should not be sent I believe, as it is optional and with sanitization on, it should be ignored.

**Comment by Qard** [comment]
The QueryArgs object didn't get populated, but it still sent an empty object. I can make it exclude the key altogether when the object is empty.

**Comment by Qard** [comment]
Here's some updated traces.

Without sanitization:
https://stephenappneta.tv.appneta.com/traces/view/E9DB8A0F11C3F51F43C72904C562EC403AC0C536/1-0

With sanitization:
https://stephenappneta.tv.appneta.com/traces/view/C74121FEDF38C3E814C9E88371E60790A2E398B6/1-0

Query truncation:
https://stephenappneta.tv.appneta.com/traces/view/CBA6F709F510289774B7FD66465179757BFA3A8C/1-0

The QueryTruncated key appears to be present in rawview, but doesn't appear in raw span data. Not sure if that is normal.

**Comment by MikeA-** [comment]
Looks good to me.  Yeah, the QueryTruncated flag helps internally but isn't surfaced.

**Pull request merged**
